import Button from "@/components/common/Button";
import Toggle from "@/components/common/Toggle";
import Head from "next/head";

import ChevronDown from "@/components/icons/ChvronDown";
import Mail from "@/components/icons/Mail";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="fixed top-0 w-full text-center pr-4 bg-emerald-950 text-white py-2 ">
          <Toggle />
        </div>
      <div className="flex flex-col gap-8 justify-center items-center h-screen bg-bg-primary text-text-primary font-medium text-xl">
        <p>Hello Champ!</p>
        <div className="flex flex-row gap-4">
          <Button variant="primary">
            Sign in
          </Button>
          <Button variant="primary" iconLeft={Mail} >
            Sign up
          </Button>
          <Button variant="primary" iconRight={ChevronDown}>
            Select
          </Button>
        </div>
      </div>
    </>
  );
}
